<?php

namespace app\models\ar;

use Yii;

/**
 * This is the base ActiveRecord class
 *
 */
class BaseAR extends \yii\db\ActiveRecord
{
    public function beforeSave($insert)
    {
        if(isset($this->meta_title) && empty($this->meta_title)) {
            $this->meta_title = null;
        }
        if(isset($this->meta_description) && empty($this->meta_description)) {
            $this->meta_description = null;
        }
        if(isset($this->meta_keywords) && empty($this->meta_keywords)) {
            $this->meta_keywords = null;
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
