<?php

namespace app\models\ar;

use Yii;

/**
 * This is the model class for table "params".
 *
 * @property int $id
 * @property string|null $popup_banner
 * @property string|null $popup_banner_link
 * @property string|null $popup_banner_2
 * @property string|null $popup_banner_link_2
 * @property int|null $main_domain
 * @property string|null $phone
 * @property string|null $email
 * @property string|null $meta_title_product
 * @property string|null $meta_desc_product
 * @property string|null $meta_title_category
 * @property string|null $meta_desc_category
 * @property string|null $meta_title_brand
 * @property string|null $meta_desc_brand
 * @property string|null $meta_title_manufacturer
 * @property string|null $meta_desc_manufacturer
 * @property string|null $meta_title_news
 * @property string|null $meta_desc_news
 * @property string|null $meta_title_page
 * @property string|null $meta_desc_page
 * @property string|null $meta_title_main
 * @property string|null $meta_desc_main
 * @property string|null $meta_keywords_product
 * @property string|null $meta_keywords_category
 * @property string|null $meta_keywords_brand
 * @property string|null $meta_keywords_manufacturer
 * @property string|null $meta_keywords_news
 * @property string|null $meta_keywords_page
 * @property string|null $meta_keywords_main
 */
class Params extends \yii\db\ActiveRecord
{
    public function afterDelete()
    {
        if (isset($this->img)) {
            if (file_exists(Yii::getAlias('@static/' . $this->popup_banner))) {
                unlink(Yii::getAlias('@static/' . $this->popup_banner));
            }
            if (file_exists(Yii::getAlias('@static/' . $this->popup_banner_2))) {
                unlink(Yii::getAlias('@static/' . $this->popup_banner_2));
            }
        }

        parent::afterDelete(); // TODO: Change the autogenerated stub
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
          'id'                      => 'ID',
          'popup_banner'            => 'Банер с акцией пром мебель',
          'popup_banner_2'          => 'Банер с акцией антистатическая мебель',
          'popup_banner_link'       => 'Ссылка банера с акцией пром мебель',
          'popup_banner_link_2'     => 'Ссылка банера с акцией антистатическая мебель',
          'main_domain'             => 'Основной поддомен',
          'phone'                   => 'Основной телефон',
          'email'                   => 'Основной e-mail',
          'meta_title_product'      => 'Meta Title Product',
          'meta_desc_product'       => 'Meta Desc Product',
          'meta_title_category'     => 'Meta Title Category',
          'meta_desc_category'      => 'Meta Desc Category',
          'meta_title_brand'        => 'Meta Title Brand',
          'meta_desc_brand'         => 'Meta Desc Brand',
          'meta_title_manufacturer' => 'Meta Title Производителя',
          'meta_desc_manufacturer'  => 'Meta Desc Производителя',
          'meta_title_news'         => 'Meta Title News',
          'meta_desc_news'          => 'Meta Desc News',
          'meta_title_page'         => 'Meta Title Page',
          'meta_desc_page'          => 'Meta Desc Page',
          'meta_title_main'         => 'Title главной страницы',
          'meta_desc_main'          => 'Meta description главной страницы',
        ];
    }

    public function beforeSave($insert)
    {
        if (!$this->isAttributeChanged('popup_banner')) {
            return parent::beforeSave($insert);
        }
        if (!$this->isAttributeChanged('popup_banner_2')) {
            return parent::beforeSave($insert);
        }

        $tmpImgs = explode(',', $this->popup_banner);
        $tmpImgs2 = explode(',', $this->popup_banner_2);

        //  Повторно проверяем входные данные
        if (!is_array($tmpImgs)) {
            return $this->addError('popup_banner', 'Проблемы с сохранением изображения');
        }
        if (!is_array($tmpImgs2)) {
            return $this->addError('popup_banner_2', 'Проблемы с сохранением изображения');
        }

        //  Валидные ли данные и есть ли данные изображения
        foreach ($tmpImgs as $tmpImg) {
            if (!file_exists(Yii::getAlias('@webroot' . $tmpImg))) {
                return $this->addError('popup_banner', 'Проблемы с сохранением изображения');
            }
        }
        foreach ($tmpImgs2 as $tmpImg) {
            if (!file_exists(Yii::getAlias('@webroot' . $tmpImg))) {
                return $this->addError('popup_banner_2', 'Проблемы с сохранением изображения');
            }
        }

        //  Записываем новые файлы
        foreach ($tmpImgs as $tmpImg) {
            $imgPath = Yii::getAlias('@webroot' . $tmpImg);
            $pathInfo = pathinfo($imgPath);
            $this->popup_banner = $pathInfo['basename'];
        }
        foreach ($tmpImgs2 as $tmpImg) {
            $imgPath = Yii::getAlias('@webroot' . $tmpImg);
            $pathInfo = pathinfo($imgPath);
            $this->popup_banner_2 = $pathInfo['basename'];
        }

        return parent::beforeSave($insert);
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
          [['main_domain'], 'integer'],
          [
            [
              'meta_title_product',
              'meta_desc_product',
              'meta_title_category',
              'meta_desc_category',
              'meta_title_brand',
              'meta_desc_brand',
              'meta_title_manufacturer',
              'meta_desc_manufacturer',
              'meta_title_news',
              'meta_desc_news',
              'meta_title_page',
              'meta_desc_page',
              'meta_title_main',
              'meta_desc_main',
              'meta_keywords_product',
              'meta_keywords_category',
              'meta_keywords_brand',
              'meta_keywords_manufacturer',
              'meta_keywords_news',
              'meta_keywords_page',
              'meta_keywords_main',
              'meta_title_series',
              'meta_desc_series',
              'meta_keywords_series',
            ],
            'string'
          ],
          [
            ['popup_banner', 'popup_banner_2', 'popup_banner_link', 'popup_banner_link_2', 'phone', 'email'],
            'string',
            'max' => 255
          ],
        ];
    }

    /**
     * @return self
     */
    public static function get()
    {
        if ($param = self::find()->one()) {
            return $param;
        } else {
            return new self();
        }
    }

    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'params';
    }
}
